- index.html
> Adds a simple boilerplate html file

- .gitignore
- css/input.css
- css/styles.css
- index.html
- package-lock.json
- package.json
- pages/about-page.html
- pages/contact-page.html
- pages/meet-the-children.html
- pages/our-work.html
- pages/support-page.html
- src/css/styles.css
- tailwind.config.js
Made boilerplate for:
-[] About us page 
-[] contact us page 
-[] meet the children page
-[] our work page
-[] support us page
added all of the files in a folder called pages. 
deleted the src folder that we did not need.
> 56 abouthtml and tailwind 

- css/styles.css
- index.html
- tailwind.config.js
-[] Add fonts to meta
-[] Add fonts to tailwind.config.js
> added fonts

- css/input.css
- css/styles.css
- index.html
-[] created the regButton
-[] created the altButton
> 61 button component tailwind

- tailwind.config.js
> Added color component classes

- pages/gallery-page.html
> Adds boilerplate, title and meta description

- index.html
> Added meta description to home page

- pages/children-specific-article.html
Added title and meta description (may be changed later).
> Created HTML boilerplate for Children Specific Article page

- pages/our-work.html
Added a meta description to our-work.html
> Added meta description to our-work page

- pages/blog.html
> Created boilerplate including page title and meta description.

- css/styles.css
- index.html
text and images are placeholders, and there will be changes to it in the future.
> 73 create html and style   section 3   home page

- css/styles.css
- index.html
Used the placeholder images. Since the images are very different sizes the styling are not all symmetrical yet. I think the image-sizes will be fixed later.
> Created HTML and style for home page section 4

- css/styles.css
- index.html
"read more" function missing, we will return to that.
look past images position - these are just placeholders, and we will return later with the correct images.
> Added section 2

- css/styles.css
- index.html
- pages/meet-the-children.html
Also fixed code indentation mistake on index.html in section 4.
> Created HTML and style section 2 on Meet the children page

- pages/meet-the-children.html
Content added and styled for section 1
> created section 1 for meet-the-children.html

- css/styles.css
- index.html
- pages/about-page.html
- pages/blog-post.html
- pages/blog.html
- pages/children-specific-article.html
- pages/contact-page.html
- pages/gallery-page.html
- pages/meet-the-children.html
- pages/news.html
- pages/our-work.html
- pages/support-page.html
Changed all image paths to correct format so it works on live page, not just locally
> Fixed image paths for all html pages

- pages/support-page.html
- tailwind.config.js
> 219 create html and style   support us page

- index.html
- pages/about-page.html
- pages/blog-post.html
- pages/blog.html
- pages/children-specific-article.html
- pages/gallery-page.html
- pages/meet-the-children.html
- pages/news.html
- pages/our-work.html
- pages/support-page.html
> Adds font awesome link

- pages/blog-post.html
> Created HTML and Style - Section 3 - Blogpost page

- pages/news.html
- [ ] Styled elements based on design
- [ ] Followed QA dev rules
> Created HTML and Style - section 4 - News page

- pages/news-post.html
> Created news-post.html, section 2

- pages/blog.html
- tailwind.config.js
Changed the html in branch 134 because of merge conflict. Made new branch, and started over.
> Changed html in 134

- css/input.css
- pages/meet-the-children.html
Added page-buttons in section 2 on Meet-the-children page
> Fixed pagebutton-elements that I forgot last time

- js/blog.js
- js/blog.mjs
> Created blog js file

- css/input.css
> Styled states for button components

- css/input.css
- pages/our-work.html
Also removed white background for the flag-SVG's because the background image on this page covers the header leading to the background of the SVG's being visible in this case, which is not wanted.
> Fixed image pathing in header after files were moved.

- pages/about-page.html
Section 3 defined and styled.
Needs media query
> Section 3 - about page

- css/input.css
- pages/our-work.html
Added content in section 2 - Our Work page
> Section 2 - Our Work page

- pages/404.html
> Boilerplate for 404 page

- pages/about-page.html
Section 5 is defined and styled based on the design. Needs media query.
> Section 5 - about

- pages/about-page.html
Section 4 defined and styled based on the design. Needs media query
> Section 4 - about page

- pages/privacy-policy.html
> Made file for privacy policy and added boilerplate

- pages/gallery-page.html
> 293 create html and style   section 1   gallery page

- pages/gallery-page.html
> Adds section 3 for gallery page

- pages/meet-the-children.html
> Adds section 3 to meet the children page

- pages/gallery-page.html
> Adds section 4 to gallery page

- index.html
- pages/about-page.html
- pages/children-specific-article.html
- pages/contact-page.html
- pages/event.html
- pages/gallery-page.html
- pages/meet-the-children.html
- pages/news-post.html
- pages/news.html
- pages/our-work.html
- pages/support-page.html
- pages/terms-and-conditions.html
> 316 move search bar overlay to header on all pages

- pages/our-work.html
> Put "subscribe to newsletter" in its own section - our work page

- index.html
> Put "Subscribe to newsletter" in its own section

- pages/privacy-policy.html
> Adds meta description and title + adds head links

- pages/privacy-policy.html
> Adds header to privacy policy page

- index.html
- js/calendar.mjs
The placeholder calendar has been replaced with a functional calendar. Current date and hovered dates have their background set to the sunset variable.
The dates which are bordered are (placeholder) event dates which can be found in the calendar.mjs file:
> Create calender for upcoming events

- index.html
Design on the footer is updated.
Also added links to the other pages.
Needs to be add to rest of the pages.
> Update on the footer

- pages/our-work.html
> Added footer to our-work.html

- pages/event.html
> Added footer to event.html

- pages/news.html
> Added footer to news.html

- pages/gallery-page.html
> Added footer to gallery-page.html

- pages/support-page.html
> Added footer to support-page.html

- pages/news-post.html
> Added footer to news-post.html

- pages/contact-page.html
> Added footer to contact-page.html

- pages/privacy-policy.html
> Added footer to privacy-policy.html

- pages/terms-and-conditions.html
> Added footer to terms-and-conditions.html

- pages/about-page.html
> Added footer to about-page.html

- index.html
- js/calendar.mjs
- js/events-list.mjs
1. Added "events-list.mjs"
2. Exported a variable from "calendar.mjs" to use in the event-list.
3. Replaced the placeholder event-list in "index.html".
4. Applied tailwind for the event-list.
The event list is now generated with javascript, the tailwind-css is applied by the "ordered-list" parent.
The events are sorted by date then a maximum of 5 events are displayed to avoid breaking the layout.
edit: Past events are filtered out.
Each event is now clickable and has its own "href" which it gets from the event variable.
> JS event-list

- js/modals.mjs
- pages/support-page.html
function toggleModal() {
let modal = document.querySelector("#volunteer-modal");
modal.classList.toggle("hidden");
}
//Opens the modal
document.querySelector(".volunteer-form-btn").addEventListener("click", toggleModal);
//Hides the modal
document.querySelector("#close-icon").addEventListener("click", toggleModal);
> Added open and close functionality for volunteer modal.

- pages/contact-page.html
> Footer path corrections and adds logo link - contact page

- js/general.mjs
- js/ourWork.mjs
- pages/our-work.html
> 413 make function to expand to make more of the text readeble when pressing read more contact us page

- pages/404.html
Footer did not existed on this page, so i added it with updated href links and link to the logo
> Update href links in footer - 404.html

- js/modals.mjs
- pages/support-page.html
> Added modal to donation and fundraising.

- index.html
> Updated newsletter section

- languageSelect/README.md
- languageSelect/index.html
Created separate folder to show the proper way to use the language switcher function with the sample html layout.  
Created README file to explain the usage of the function.
> add function to switch the language

- README.md
- languageSelect/README.md
- languageSelect/index.html
- pages/about-page.html
Below is the JavaScript code that controls the animation of gallery images.
function enlargeImage(image) {
image.classList.add('enlarged');
}
function shrinkImage(image) {
image.classList.remove('enlarged');
}
function fadeInImage(image) {
image.style.opacity = '0';
let opacity = 0;
const fadeInInterval = setInterval(() => {
if (opacity < 1) {
opacity += 0.05;
image.style.opacity = opacity;
} else {
clearInterval(fadeInInterval);
}
}, 50);
}
> 232-gallery-js-file

- languageSelect/README.md
- languageSelect/index.html
I was able to implement the steps for comments in a blog JS.
Below are my steps for implementing comments in a blog JS.
// Step 1: Define an array to store the comments
let comments = [];
// Step 2: Define a function to add a new comment
function addComment(author, text) {
// Step 2a: Create a new comment object
let newComment = {
author: author, // Step 2b: Assign the author of the comment
text: text,     // Step 2c: Assign the text content of the comment
date: new Date() // Step 2d: Assign the current date to the comment
};
// Step 2e: Push the new comment to the comments array
comments.push(newComment);
}
// Step 3: Define a function to display all comments
function displayComments() {
// Step 3a: Loop through each comment in the comments array
for (let i = 0; i < comments.length; i++) …
> Make commented list Blog JS

- js/toggle-utils.mjs
- pages/gallery-page.html
Below is the JavaScript code that controls the animation of gallery images.
function enlargeImage(image) {
image.classList.add('enlarged');
}
function shrinkImage(image) {
image.classList.remove('enlarged');
}
function fadeInImage(image) {
image.style.opacity = '0';
let opacity = 0;
const fadeInInterval = setInterval(() => {
if (opacity < 1) {
opacity += 0.05;
image.style.opacity = opacity;
} else {
clearInterval(fadeInInterval);
}
}, 50);
}
> Gallery JS file

- package-lock.json
- tailwind.config.js
I added new colors as suggested in the issue description.
> adds 2 new colors and deletes 2 old ones.

- index.html
- pages/404.html
- pages/about-page.html
- pages/contact-page.html
- pages/event.html
- pages/gallery-page.html
- pages/news-post.html
- pages/news.html
- pages/our-work.html
- pages/privacy-policy.html
- pages/support-page.html
- pages/terms-and-conditions.html
Me and Christian have change the footer and made it responsive. we hade som issue with the break point in tailwind. but it worked after we got some help from conor
Closes #152
> 152implement responsive

- pages/gallery-page.html
Adjusted class font-normal to font-sans to make it Montserrat for the h2 and button, I also adjusted the classes for the buttons using p-3 and px-8 instead of set height and widths.
> 603# adjusting fonts on the gallery page

- pages/about-page.html
- pages/event.html
I have moved Support and Future Ambitions under the MFF suported, I have also change the mt from 16 to 10 and i have set the first text to text center
> Pull 599 adjust position of elements on about page

- index.html
try to fix the langue button in the header on the index page
> Change the langue button in the header on the index page

- index.html
test to see if the global icon works
> test to see if the global icon works

- pages/event.html
Added font family and font sizes to h1 and h2.
> 605 change fonts in h1 and h2 to montserrat in events page

- index.html
Path is fixed to the image of three childeren in index
> fixed path to image of three childeren

- index.html
responsiveness added to sections 4-7
> responsiveness sections 4 to 7

- index.html
Adjusting the tailwind classes on the sign-up button on the homepage to closer resemble the design.
> Hover styling added to the Sign-up button on the homepage

- index.html
- pages/404.html
- pages/about-page.html
- pages/contact-page.html
- pages/event.html
- pages/gallery-page.html
- pages/news-post.html
- pages/news.html
- pages/our-work.html
- pages/privacy-policy.html
- pages/support-page.html
- pages/terms-and-conditions.html
added favicon to all pages in html
> added favicon on all pages

- index.html
I tried making the images a little bigger aswell to help with the empty space on the sides. Took the liberty to remove mint green background on the gallery section as it was not in the Figma design.
> Added responsivness and smaller margin

- pages/news-post.html
Adjusted the pictures and text to closer represent the design. Decided to remake the entire second section as I found it easier to work of the section with correct margins. Further added some of the missing text and fixed the 'next post' button
> Images + text / news-post.html

- pages/news.html
Changes made to "Latest news" section.
> 638 fix font sizes and button styling on latest news section news page

- pages/terms-and-conditions.html
> 590 create html and style terms and conditions

- pages/about-page.html
Added the correct color from the tailwind config to the staff member cards
Made the cards background color transparent for mobile design
> Update Background Color for Staff Member Cards "about" page 

- pages/event.html
Update the font to normal ang gap to 0.25 rem.
> Update font and gap

- pages/news-post.html
Added the missing main heading "MMF Culture and Arts Festival" to the news-post page
Styled to look like the desktop design
> Added missing main heading

- pages/gallery-page.html
- pages/news-post.html
- pages/news.html
- pages/our-work.html
Updated the following pages to display the correct logo: 
- our work
- news
- news-post
- gallery-page
The logo png was added to assets in issue 657, so I added the correct link and matched the responsive tailwind styling from that issue
(issue #663, branch 657)
> change to original logo

- index.html
All the "read" more buttons missed the border, hover and font-sizing, that is fixed. And also the path to our staff picture.
> fixed path and button mistakes from another merge

- index.html
Added font sizes and changed card sizes for section 3.
> fixes font inconsistencies in index

- index.html
- pages/404.html
- pages/about-page.html
- pages/contact-page.html
- pages/event.html
- pages/gallery-page.html
- pages/news-post.html
- pages/news.html
- pages/our-work.html
- pages/privacy-policy.html
- pages/support-page.html
- pages/terms-and-conditions.html
Updated the donate button in the header on all pages
Styled for mobile and desktop
> 564 update donate button header

- index.html
- pages/404.html
- pages/about-page.html
- pages/contact-page.html
- pages/event.html
- pages/gallery-page.html
- pages/news-post.html
- pages/news.html
- pages/our-work.html
- pages/privacy-policy.html
- pages/support-page.html
- pages/terms-and-conditions.html
> Have change the icon gap

- index.html
- js/calendar.mjs
Reverts NoroffFEU/musikkforandrerliv.no#692
This merge has conflicts with the calendar - reverting it
> Revert "Update font and size"

- pages/event.html
added border to button previous event (and also right path to logo in the footer.
> added border to button previous event

- package-lock.json
- package.json
- src/store/index.js
- Installs Zustand as the global state management solution.
- Creates the store/ folder inside src/.
- Implements a centralized index.js to simplify imports.
- Add and configure Zustand in the project.
- Ensure a clear and modular store structure.
- Enable simplified imports from store/index.js
- Install dependencies (if not already installed).
- Check the store/ folder inside src/.
- Verify that stores can be imported from store/index.js, for example:
`import { useExampleStore } from '@/store';`
This PR establishes the foundation for state management using Zustand, ensuring a clean and scalable structure. Additional stores can be added in future tasks as needed.
> install zustand and create index.js to keep the exports

- src/pages/home.jsx
Add home.jsx under src/pages and create HomePage component.
In HomeComponent, I added section elements with different id.
I also created homePage folder and add file for each section's component.
> Setup folder

- src/store/UIStore/createUIStore.js
Add Zustand store for managing modal visibility.
Create a state for changing the visibility of a modal.
- import useModalStore
- Use toggleModal(), openModal(), and closeModal() to verify that the modal's visibility state updates correctly
- Optionally, log isModalOpen to the console to confirm state changes
> Add Zustand store for managing modal visibility

- package-lock.json
- package.json
- src/App.jsx
- src/i18n.js
Installs an configure React i18next.
Install react-i18next and i18next, Create an i18n.js configuration file and Set up I18nextProvider in App.js.
Run the app in dev mode: npm run dev.
Click the NO Button.
Verify that the language switches to Norwegian.
I am not sure if it is possible to test this config before the translation.json files are added
> 736 install and configure react i18next

- src/App.jsx
- src/components/lang/language-icons.jsx
- src/components/lang/language-option.jsx
- src/components/lang/select-language-button.jsx
Adds a dropdown component containing available language translation.
Implement Language Switcher UI
[#766](https://github.com/NoroffFEU/musikkforandrerliv.no/issues/766)
npm run dev => navigate to '/'
1.  Click flag icon
-  Dropdown opens
2. Select language
- Dropdown closes
- Flag icon changes to selected language
3. Open menu again and click outside
- Dropdown closes
3. Test accessibility by using keyboard
5. Resize window to mobile and re-test
Hook is not implemented and selecting a language will not translate anything.
> feat: Language picker dropdown

- src/store/UIStore/useUIStore.js
- src/store/index.js
- Importing the states in src/store/index.js
- State for sidebar implemented
- Implement a state using zustand for the sidebar.
- Fix imports for the given states to the index.js file
- Check the repo if the code is implemented
- Nope!
> Sidebar state and importing

- src/store/UIStore/useUIStore.js
- src/store/index.js
- Added new name to sidebar state function
- Added more js docs for clarity
- Added example of usage of the function
- rename the function name to a more descriptive name
- add a JSDoc description at the top (above the properties)
- add an @example of usage of the function
- Check the repo to see the reflected files
Closes #832
> Fix sidebar function

- src/store/UIStore/useUIStore.js
The Zustand store for darkmode is added and finished, with JS docs that describes the store and the properties.
Create a Zustand state for changing between light and dark themes.
- Import useDarkModeStore in your application.
- Test each function in the console:
Open the Developer Console (F12 → Console).
Run the following commands to check if the state updates correctly:
useDarkModeStore.getState().toggleDarkMode(); 
useDarkModeStore.getState().enableDarkMode(); 
useDarkModeStore.getState().disableDarkMode(); 
Verify that isDarkMode updates as expected.
- Check Local Storage:
Open DevTools → Application → Local Storage.
Locate the key darkMode.
Toggle dark mode and verify that darkMode updates between "true" and "false" correctly.
The CSS team must use the dark class in Tailwind to apply …
> Added Store for DarkMode

- src/store/index.js
The darkmode store is now added to index.js, which it was not in the last PR: https://github.com/NoroffFEU/musikkforandrerliv.no/pull/837.
> Added the darkmode store to index.js

- src/locales/locales.en.json
Provides locales.en.json file for the i18n translation hook.
Create English Translation JSON file
[#772](https://github.com/NoroffFEU/musikkforandrerliv.no/issues/772)
This cannot be tested yet.
When every translation file is done. We will merge developer branch into translation branch and then test/read translations.
> update: add supportedBy around description in history introduction array

- public/admin/config.yml
Adds blog post collection folder with properties.
It needs correct path for storing posts, I just set a temporary path.
Also needs to add necessary field properties.
Can't be tested at the moment.
> Adds blog post collection folder

- src/components/homePage/Footer.jsx
Create Footer.jsx page and Footer component
Still need to link pages to links
> 748 create footer component

- src/App.jsx
- src/components/ErrorBoundary.jsx
- src/components/LoadingSpinner.jsx
- src/pages/About.jsx
- src/pages/Contact.jsx
- src/pages/Home.jsx
- src/pages/TestTranslations.jsx
- src/routes/index.jsx
Added loading indicators for route changes
Implemented error boundaries for broken routes
Add loading indicators for route changes
Implement error boundaries for broken routes
Ensure loading indicators appear correctly
Verify error boundaries display meaningful messages
Test unexpected errors to confirm smooth recovery
> Feature- Loading spinner and error boundaries

- src/components/homePage/historySection.jsx
Implemented the history section
> history section

- src/App.jsx
- src/components/Footer.jsx
- src/pages/Home.jsx
* Fix homepage loading issues
* Fix footer input missing onChange handler
Fixing the app
Manually QA that the page loads
> 932 Fix homepage

- public/admin/config.yml
Adds labels and properties to Support Us page
> added support-us in collection

- public/admin/config.yml
Adds "Our work" file in pages collection with properties excluding necessary input fields which will be added later on.
To add necessary inputs to the fields property.
Needs the correct input fields before testing.
> Adds "Our work" file in pages collection

- public/admin/config.yml
- Adds about us page to cms config
Needs to add necessary fields properties
The page is visible, but not much to do with it yet.
> feat: add About Us page to CMS config

- public/admin/config.yml
Adds contact pag to CMS
Fill in fields 
Page is visible in cms
> feat: add cotact page to config.yml

- src/hooks/useLanguageSwitcher.jsx
- src/pages/TestTranslations.jsx
- updates the flag icons when clicking test translation buttons
- Ensures the SelectLanguageButton reflects language changes triggered from TestTranslations.
- Uses an event listener on localStorage to sync language updates across components.
- Dispatches a manual storage event to ensure immediate UI updates.
1. Click a flag icon in the SelectLanguageButton - The language and icon should update.
2. Click a test translation button in TestTranslations - The flag icon should immediately reflect the change.
3. Refresh the page - The last selected language should persist.
Previously, changing the language from TestTranslations did not update the flag icons due to missing state synchronization.
> Update language selector to change flag when clicking Test buttons

- src/pages/Home.jsx
> feat: add GallerySection to Home page

- src/components/homePage/gallerySection.jsx
- src/pages/Home.jsx
Implemented gallerysection for homepage
Reusable image component
Loads images from a JSON file
Uses lazy loading for performance
Responsive grid layout (Tailwind CSS)
Includes ARIA attributes for accessibility
Keyboard navigation enabled
> feat: implement responsive GallerySection

- src/pages/OurWork.jsx
- src/routes/index.jsx
Set up Our work page
Add OurWork.jsx file, with boilerplate 
Add route to the page in src/routes/index.jsx
Add new folder ourWorkPage in src/components/
Navigate to the route for the page in the browser and confirm that the boilerplate component renders correctly - This have been tested, and works correctly.
> 927 setup our work page

- src/components/LatestNews.jsx
- src/pages/News.jsx
- src/routes/index.jsx
> Latest news section

- public/locales/locales.en.json
- src/components/Navbar.jsx
- Removes hardcoded text in the navbar
- Added useTranslation for navbar to change language
- Updated en.json file with missing translations in "common" - "header"
I see there are dupicates in the navbar. I updated useTranslation for all places since im not sure wich one we will keep.
> Update translation navbar

- src/components/homePage/calenderSection.jsx
- src/pages/OurWork.jsx
Adds the Calendar component to the OurWork page and centers the text to match the Figma design.
- Imported and rendered the Calendar component on the OurWork page
- Centered the relevant text content to follow the layout from the Figma design
- Navigate to the OurWork page
- Confirm that the Calendar component is displayed
- Check that the text is centered as shown in the Figma file
> Add calendar to ourwork page, center text in responsive

- src/components/Footer.jsx
Removes hardcoded text for the newsletter in the footer
Test by clicking language buttons
> Update: replaced hardcoded text in newsletter inside the footer

- src/data/our-work-page.json
This PR adds the json data document for the Our Work page, with title, content, image and imageAlt for each category.
"This issue will add a json document to the repository with all the data we need in the section layouts for each work area."
- Use online JSON validator
- Manually check each section
- Verify no syntax errors
-
> Added our-work-page.json

- package-lock.json
- src/components/buttons/reusableButton.jsx
> created buttons that is reusable

- src/components/buttons/BackToTop/index.jsx
Adds a floating "Back to Top" button with smooth scrolling and accessibility improvements.
- Implement a button that appears when scrolling past 300px
- Enable smooth scrolling to the top on click
-Improve accessibility with aria-label
- import it into a page
- Scroll down the page past 300px
- Verify that the "Back to Top" button appears
- Click the button and confirm it smoothly scrolls to the top
There is already a back to top button created in `/homepage/historySection.jsx` This is not made by me.
> Create back to top button

- src/data/our-work-page.json
This PR addresses an issue with the JSON file where the image paths were incorrect. The changes ensure that all image paths are corrected to their proper locations.
- Reviewed the JSON structure to identify incorrect or broken image paths.
- Updated all image paths to reflect the correct directory structure.
- Ensured consistency across all entries in the JSON file to prevent similar issues in the future.
- Clone the branch associated with this PR.
- Open the updated JSON file and verify that all image paths are correctly pointing to the intended assets.
> Update our-work-page.json with the correct image paths

- src/components/aboutUsPage/staffSection.jsx
- src/data/about-us-page-content.json
- src/pages/About.jsx
- Added dark theme header ''our staff'' placeholder values
- Created individual staff cards with placeholder props and dynamic alternating layout rendering
- Corrected surname of staff member in json file
- Corrected newline tags in json file
As far as i can tell dark mode has not been implemented yet, so just placeholder values for now in the "our staff" header
> 960 create props for our staff section

- src/components/Footer.jsx
- src/components/Navbar.jsx
- src/pages/News.jsx
Add Anchor tags to NavLinks and Links and corresponding ids to matching sections
> 948 improve navigation user interaction part 1 add anchor links

- public/admin/config.yml
Adds global i18n configuration with `en` as the default locale.
> added global i18n configuration with english as default language.

- src/pages/NewsPost.jsx
- src/routes/index.jsx
Create a NewsPost.jsx file in src/pages and make sections for each of the headlines according to the design.
> 1025-Setup New page structure

- src/components/ourWorkPage/categorySection.jsx
This PR implements a "Read More" button in the category section of the page. The button currently logs a message to the console as a placeholder for when the page functionality is ready. It will eventually lead to a new page displaying the full content about the category.
- Add the "Read More" button to the category section of the page.
- Implement the button functionality, which currently logs to the console when clicked (a placeholder for future navigation).
- Apply the required styling to the button using Tailwind CSS.
- Ensure accessibility features are in place, including aria-label for screen readers.
1. Navigate to the category section on the page.
2. Click the "Read More" button.
3. Observe the console log to confirm the action is triggered (this is the placeholder for future page …
> Interactivity on read more button

- public/locales/locales.en.json
- public/locales/locales.mg.json
- public/locales/locales.no.json
- src/components/homePage/calenderSection.jsx
- src/components/homePage/gallerySection.jsx
- src/components/homePage/historySection.jsx
- src/components/homePage/staffSection.jsx
- src/components/homePage/supportSection.jsx
- src/components/homePage/volunteerSection.jsx
- src/components/homePage/workSection.jsx
Replace all texts with translation keys
Switching language by changing language in header
> 1022 implement translation functionality for the landing page home page

- public/admin/config.yml
added no and mg locals
Fallback rules not possible in cms itself. 
It is added in the i18n.js file already.
> added no and mg locals

- src/components/ourWorkPage/categorySection.jsx
- src/pages/OurWorkSpecific.jsx
- src/routes/index.jsx
Set up category specific page
Set up the page Work Category Specific Page. This has not been designed yet, but we will have it ready so that the redirect can be implemented on the read more button in each work category section when it is.
- add page and boilerplate to the page
- add to router
- update the action on the read more button to redirect to this page
Navigate to Our Work page and verify that the 'read more' button redirects to the new page
> 1037 sub set up category specific page

- src/components/Footer.jsx
- src/components/MainLayout.jsx
- src/components/buttons/BackToTopButton.jsx
- src/components/homePage/gallerySection.jsx
- src/components/homePage/heroSection.jsx
- src/components/homePage/historySection.jsx
- src/pages/Gallery.jsx
- src/routes/index.jsx
This PR added a back to top button across all pages and alt text for images on home page. I also added the news route in routes. 
Clone branch and test if the back to top btn is on all pages and if the alt text is showing in Accessibility in console. Check if news page is found.
> Back to Top BTN  - Alt text for img on home page  - Added news route

- package-lock.json
- src/pages/Gallery.jsx
- Adds a image gallery using grid layout.
- Adds heading and a paragraph above.
The gallery has a 3-column layout on desktop, 2-column on tablet and 1-column on mobile.
- Clone branch and test if gallery is responsive by looking at the page on different screen sizes.
- Hover over images to see if the images are highlighted
> 994 develop a grid based image gallery

- src/components/aboutUsPage/staffSection.jsx
- src/index.css
added justanotherhand font to theme in index.css so it can be applied. updated staffSection to new design. closes issue (#1053)
> added justanotherhand font to theme in index.css so it can be applied. updated staffSection to new design. closes issue (#1053)

- src/components/aboutUsPage/aboutsUsSection.jsx
- src/pages/About.jsx
- A reusable InfoSection component using props
- Intro layout for the first section (text + button + image, no title)
- Standard layout for the remaining five sections (title + text + image)
- Placeholder shown when no image is provided
> Created props for About us

- src/pages/News.jsx
Add scrollIntoView({behavior : `smooth`}) to scrolling to improve user experience
> feat: add smooth scrolling to improve user experience

- src/pages/News.jsx
IT adds animation during the loadmore button in the news to fetch more articles.
Animation and smooth expansion. It adds fade-in effect and side-up effect
Clone and follow the readme file, and go to news page and click the loadmore button.
> Implemented expandable news list with smooth animations

- src/components/galleryPage/imageGallery.jsx
- src/data/landing-page-content.json
This PR implements the alt text in Accessibility in console for the gallery grid. 
Clone branch and check if you can see the alt text for the images in the grid in Accessibility in console.
> Alt text gallerygrid

- src/components/aboutUsPage/SupportersSection.jsx
- src/data/about-us-page-content.json
- src/pages/About.jsx
- Added Supporters section to About Us page
- Created new SupportersSection component
- Updated about-us-page-content.json with supporters data
- Implemented alternating color styling
- Supporters are displayed with alternating pink and black text
- Component is dynamically rendered based on JSON data
- Follows existing design patterns in the project
- Verify supporters section appears correctly
- Check color alternation
> 1003 supporters section rosario

- src/components/galleryPage/imageGallery.jsx
- src/components/homePage/gallerySection.jsx
Fixed the images on homepage so it shows. Alt text is also added.
Check if images are in gallery section on home page as well as in gallery with alt text in console accessibility.
> Fixed alt-text for homepage gallery section

- src/data/about-us-page-content.json
> Feat: Added image path for placholder image and alt text for each image

- src/pages/NewsPost.jsx
What does this PR do?
Adds navigation functionality to the news post page using "Next Post" and "Previous Post" buttons.
How should this be manually tested?
Start the dev server with npm run dev
Navigate to the /news-post route.
Click the "Next Post" button to view the next post.
Click "Previous Post" to go back.
Ensure the buttons are hidden when at the beginning or end of the post list.
> 1075 make next previous post function
